# Generated by Django 3.2 on 2021-04-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_pedidos', '0002_alter_clientes_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='address',
            field=models.CharField(max_length=30, verbose_name='Your adress'),
        ),
    ]
