# Generated by Django 3.2 on 2021-04-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_pedidos', '0003_alter_clientes_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
